### ISSUE TITLE
如何登录b站和上传？试了没反应.....

### ISSUE THREAD

**Issue by ChloeKurumi** [arm64v8a/CDNDrive-go#2]
登录
cdndrive cookie bili buvid3=EF7FF59C-2EBE-443D-84F4-56A682FF0448143101infoc; blackside_state=1; rpdid=xxxxxxxxxxx; finger=1295565314; PVID=1; buvid_fp=EF7FF59C-2EBE-443D-84F4-56A682FF0448143101infoc; buvid_fp_plain=EF7FF59C-2EBE-443D-84F4-56A682FF0448143101infoc; LIVE_BUVID=xxxxxxxx; bsource=search_baidu; video_page_version=v_old_home; CURRENT_QUALITY=0; fingerprint=2875a2f6b5fbe647e179208c0169d2af; SESSDATA=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; bili_jct=a60a775f56e7dbd3afdc064a61a6966c; DedeUserID=255706; DedeUserID__ckMd5=xxxxxxxxxxxxxx; sid=c96cs7rp; i-wanna-go-back=-1; b_ut=5; CURRENT_BLACKGAP=0; innersign=0; CURRENT_FNVAL=80
上传 
cdndrive upload bili PW.mp4

我输入的命令格式不对么？？也没报错，光是提示，而且也看不了自己有没有登录........求给个示例.......

**Comment by arm64v8a** [comment]
你是不是搞错项目了
这是 CDNDrive 的命令，不是 CDNDrive-go 的

**Comment by ChloeKurumi** [comment]
> 

没搞错啊，和CDNDrive用法不一样嘛？求示例.....这个怎么用啊....登录参数怎么写?

**Comment by arm64v8a** [comment]
不一样，自己看说明
